## Step 1 - Data Engineering

#The climate data for Hawaii is provided through two CSV files. Start by using Python and Pandas to inspect the content of these files and clean the data.

#* Create a Jupyter Notebook file called `data_engineering.ipynb` and use this to complete all of your Data Engineering tasks.

#* Use Pandas to read in the measurement and station CSV files as DataFrames.

#* Inspect the data for NaNs and missing values. You must decide what to do with this data.

#* Save your cleaned CSV files with the prefix `clean_`.

In [ ]:
import pandas as pd
import numpy as np
import csv

In [2]:
# read the provided CSV data into DataFrames
stations="hawaii_stations.csv"
weather="hawaii_measurements.csv"
stations_data=pd.read_csv(stations,encoding="iso-8859-1")
weather_data=pd.read_csv(weather,encoding="iso-8859-1")
stations_df=pd.DataFrame(stations_data)
weather_df=pd.DataFrame(weather_data)

In [3]:
weather_df.count()

station    19550
date       19550
prcp       18103
tobs       19550
dtype: int64

In [4]:
# Checking for duplicates in the measurements DataFrame
weather_df.duplicated().sum()

0

In [5]:
# Clean the NaN's from the precipitation column (convert to zero)
weather_df['prcp'] = weather_df['prcp'].fillna(0)

In [6]:
weather_df.count()

station    19550
date       19550
prcp       19550
tobs       19550
dtype: int64

In [7]:
weather_df.head(100)

        station        date  prcp  tobs
0   USC00519397  2010-01-01  0.08    65
1   USC00519397  2010-01-02  0.00    63
2   USC00519397  2010-01-03  0.00    74
3   USC00519397  2010-01-04  0.00    76
4   USC00519397  2010-01-06  0.00    73
5   USC00519397  2010-01-07  0.06    70
6   USC00519397  2010-01-08  0.00    64
7   USC00519397  2010-01-09  0.00    68
8   USC00519397  2010-01-10  0.00    73
9   USC00519397  2010-01-11  0.01    64
10  USC00519397  2010-01-12  0.00    61
11  USC00519397  2010-01-14  0.00    66
12  USC00519397  2010-01-15  0.00    65
13  USC00519397  2010-01-16  0.00    68
14  USC00519397  2010-01-17  0.00    64
15  USC00519397  2010-01-18  0.00    72
16  USC00519397  2010-01-19  0.00    66
17  USC00519397  2010-01-20  0.00    66
18  USC00519397  2010-01-21  0.00    69
19  USC00519397  2010-01-22  0.00    67
20  USC00519397  2010-01-23  0.00    67
21  USC00519397  2010-01-24  0.01    71
22  USC00519397  2010-01-25  0.00    67
23  USC00519397  2010-01-26  0.04    76
24  USC00519397  2010-01-27  0.12    68
25  USC00519397  2010-01-28  0.00    72
26  USC00519397  2010-01-30  0.00    70
27  USC00519397  2010-01-31  0.03    67
28  USC00519397  2010-02-01  0.01    66
29  USC00519397  2010-02-03  0.00    67
..          ...         ...   ...   ...
70  USC00519397  2010-03-23  0.00    68
71  USC00519397  2010-03-24  0.00    74
72  USC00519397  2010-03-26  0.00    72
73  USC00519397  2010-03-27  0.00    72
74  USC00519397  2010-03-28  0.00    73
75  USC00519397  2010-03-29  0.00    74
76  USC00519397  2010-03-30  0.00    73
77  USC00519397  2010-03-31  0.00    73
78  USC00519397  2010-04-01  0.00    74
79  USC00519397  2010-04-02  0.01    74
80  USC00519397  2010-04-03  0.17    74
81  USC00519397  2010-04-04  0.15    71
82  USC00519397  2010-04-05  0.27    72
83  USC00519397  2010-04-06  0.01    75
84  USC00519397  2010-04-08  0.00    75
85  USC00519397  2010-04-09  0.01    75
86  USC00519397  2010-04-10  0.00    75
87  USC00519397  2010-04-11  0.01    73
88  USC00519397  2010-04-12  0.01    73
89  USC00519397  2010-04-13  0.00    71
90  USC00519397  2010-04-15  0.00    71
91  USC00519397  2010-04-16  0.01    68
92  USC00519397  2010-04-17  0.00    70
93  USC00519397  2010-04-18  0.00    71
94  USC00519397  2010-04-19  0.00    74
95  USC00519397  2010-04-20  0.04    71
96  USC00519397  2010-04-21  0.01    75
97  USC00519397  2010-04-22  0.00    76
98  USC00519397  2010-04-23  0.02    75
99  USC00519397  2010-04-24  0.00    75

[100 rows x 4 columns]

In [8]:
# look at data to see missing data points.
stations_df.count()

station      9
name         9
latitude     9
longitude    9
elevation    9
dtype: int64

In [9]:
# Checking for null values
stations_df.duplicated().sum()

0

In [10]:
# Checking for NaNs
stations_df.isnull().values.sum()

0

In [11]:
weather_df.to_csv("clean_hawaii_measurements.csv", index = False)
stations_df.to_csv("clean_hawaii_stations.csv", index = False)