In [12]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [13]:
#read in city data csv
city_df = pd.read_csv('city_data.csv')
city_df.head(100)

                    city  driver_count      type
0             Kelseyland            63     Urban
1             Nguyenbury             8     Urban
2           East Douglas            12     Urban
3          West Dawnfurt            34     Urban
4         Rodriguezburgh            52     Urban
5      South Josephville             4     Urban
6       West Sydneyhaven            70     Urban
7            Travisville            37     Urban
8            Torresshire            70     Urban
9              Lisaville            66     Urban
10             Mooreview            34     Urban
11            Smithhaven            67     Urban
12           Carrollfort            55     Urban
13       Port Josephfurt            28     Urban
14      Lake Jeffreyland            15     Urban
15           South Louis            12     Urban
16            West Peter            61     Urban
17       Kimberlychester            13     Urban
18            Alyssaberg            67     Urban
19              Sarabury            46     Urban
20           Yolandafurt             7     Urban
21           Edwardsbury            11     Urban
22       New Andreamouth            42     Urban
23             New David            31     Urban
24            Arnoldview            41     Urban
25          Williamshire            70     Urban
26              Lisatown            47     Urban
27             New Aaron            60     Urban
28           Swansonbury            64     Urban
29            Fosterside            69     Urban
..                   ...           ...       ...
70    South Gracechester            19  Suburban
71  East Jenniferchester            22  Suburban
72         West Paulport             5  Suburban
73    New Brandonborough             9  Suburban
74            Floresberg             7  Suburban
75           Lake Brenda            24  Suburban
76               Kyleton            12  Suburban
77            Thomastown             1  Suburban
78  South Shannonborough             9  Suburban
79            Jeffreyton             8  Suburban
80     Port Michelleview            16  Suburban
81    West Pamelaborough            27  Suburban
82             Sarahview            18  Suburban
83      New Cindyborough            20  Suburban
84            Port James            15  Suburban
85      New Samanthaside            16  Suburban
86              Paulfort            13  Suburban
87             Jasonfort            25  Suburban
88            North Tara            14  Suburban
89       East Cherylfurt             9  Suburban
90         Rodriguezview            10  Suburban
91            Tiffanyton            21  Suburban
92       Port Alexandria            27  Suburban
93        South Jennifer             6  Suburban
94            Anitamouth            16  Suburban
95           Conwaymouth            18  Suburban
96              New Lynn            20  Suburban
97             Port Jose            11  Suburban
98              Johnland            13  Suburban
99             West Tony            17  Suburban

[100 rows x 3 columns]

In [10]:
# read in rider data
ride_df = pd.read_csv('ride_data.csv')
ride_df.head(100)

                city                 date   fare        ride_id
0           Sarabury  2016-01-16 13:49:27  38.35  5403689035038
1          South Roy  2016-01-02 18:42:34  17.49  4036272335942
2        Wiseborough  2016-01-21 17:35:29  44.18  3645042422587
3        Spencertown  2016-07-31 14:53:22   6.87  2242596575892
4         Nguyenbury  2016-07-09 04:42:44   6.28  1543057793673
5        New Jeffrey  2016-02-22 18:36:25  36.01  9757888452346
6      Port Johnstad  2016-06-07 02:39:58  17.15  4352278259335
7          Jacobfort  2016-09-20 20:58:37  22.98  1500221409082
8        Travisville  2016-01-15 17:32:02  27.39   850152768361
9         Sandymouth  2016-11-16 07:27:00  21.61  2389035050524
10   New Andreamouth  2016-04-11 07:20:48   7.72  9992929847990
11     New Christine  2016-09-13 15:06:42  24.89  7918411468537
12       Stewartview  2016-03-29 05:15:56  23.88  6778235889588
13    Rodriguezburgh  2016-09-05 05:20:39   4.54  9650770953139
14  West Sydneyhaven  2016-08-02 21:18:44  12.87  7994760397230
15       Swansonbury  2016-07-11 18:42:11  39.30   744481862626
16          Lisatown  2016-07-05 18:09:14   5.82  6370359473201
17         East Erin  2016-11-03 01:03:05   7.51  4744239092530
18   Port Martinberg  2016-01-06 17:11:30   8.66  7298562820881
19       Wiseborough  2016-09-12 18:43:41  26.83  9304728540000
20       Edwardsbury  2016-02-27 03:55:54  20.17  8514523868075
21         Jacobfort  2016-06-12 17:01:29  34.47  4135673527977
22       Pamelahaven  2016-03-26 12:56:57  36.43  3015329826849
23        Fosterside  2016-08-12 11:52:41  28.08   133077693483
24         Jacobfort  2016-09-17 12:38:58  38.25  2182376146051
25  West Sydneyhaven  2016-08-23 14:49:59  36.12  5885997568611
26       West Alexis  2016-01-16 00:33:02  26.62  1574788996743
27       Carrollfort  2016-06-24 20:11:11   6.45  1092683495142
28         New David  2016-01-12 20:48:43  38.68  5229089333754
29       Stewartview  2016-10-15 05:26:40  11.74  8402784599831
..               ...                  ...    ...            ...
70      New Maryport  2016-02-10 05:36:14  23.41   397475291942
71     West Dawnfurt  2016-07-24 15:18:57  30.80  3839329929610
72         Davidtown  2016-10-12 17:56:31  24.65  9382980155712
73        West Peter  2016-08-16 23:26:16   7.25  1040904625038
74       Spencertown  2016-01-16 18:28:03  35.59  7002933670322
75    Rodriguezburgh  2016-11-21 10:41:56  26.13  6513545702246
76       Russellport  2016-09-08 17:46:03  13.81  1034339681561
77    Rodriguezburgh  2016-05-22 21:34:07   8.83  5135321621391
78       West Brandy  2016-08-19 03:53:38  17.72  1904212005602
79         South Roy  2016-11-20 02:09:58   6.81  6512612750531
80       Russellport  2016-02-02 20:46:31  18.96  7234982138755
81    Zimmermanmouth  2016-08-11 11:17:38   5.97  7276044030126
82          Sarabury  2016-06-23 05:03:41  26.82  6711035373406
83      East Douglas  2016-10-01 19:07:00  16.36  8450340983211
84       Kellershire  2016-11-02 16:34:41  15.29  7136970429336
85         Davistown  2016-02-29 22:39:26  15.58  2605125055829
86         Davistown  2016-05-26 20:42:36  12.96  3749975593991
87         Mooreview  2016-05-31 13:20:24  24.82  9881448402158
88    Zimmermanmouth  2016-08-01 20:38:52  34.95  2258161061820
89     Port Johnstad  2016-08-21 08:03:31  15.92  4308926263704
90   Port Josephfurt  2016-09-20 19:27:35  14.00  2465241563666
91      East Douglas  2016-07-19 07:42:04  11.24  8566233760392
92      East Douglas  2016-09-20 02:40:41  23.26   825335145222
93       Torresshire  2016-05-24 15:47:08  29.25  9781946552709
94       West Brandy  2016-10-04 21:18:38  20.62  1064604032088
95     New Christine  2016-01-26 13:18:17  23.52  1415478418209
96   New Andreamouth  2016-11-18 15:01:25  17.64  8669842502879
97          Lisatown  2016-10-14 09:22:04  33.40  9894794967721
98     Port Johnstad  2016-08-27 18:09:13  22.48  9410972024170
99       Wiseborough  2016-09-12 00:38:50  20.62  8634932507263

[100 rows x 4 columns]

ValueError: DataFrame constructor not properly called!

In [22]:
merge = pd.merge(city_df,ride_df, on='city_df')

KeyError: 'city_df'